name: Deploy Components
on:
  workflow_call:
    inputs:
      cli-version:
        required: false
        description: "Version of BOS CLI to use for deploy (e.g. 0.3.0)"
        type: string
        default: "0.3.1"
      deploy-account-address:
        required: true
        description: "Account under which component code should be deployed. Also the Signer"
        type: string
      signer-public-key:
        required: true
        description: "Public key for signing transactions in the format: `ed25519:<public_key>`"
        type: string
      directory-paths:
        required: true
        description: "Comma-separated paths to the directories that contain the code to be deployed"
        type: string
      environment:
        required: true
        description: "mainnet or dev"
        type: string
    secrets:
      SIGNER_PRIVATE_KEY:
        description: "Private key in `ed25519:<private_key>` format for signing transaction"
        required: true
jobs:
  deploy-widgets:
    runs-on: ubuntu-latest
    name: Deploy widgets to social.near
    env:
      BOS_DEPLOY_ACCOUNT_ID: ${{ inputs.deploy-account-address }}
      BOS_SIGNER_PUBLIC_KEY: ${{ inputs.signer-public-key }}
      DIRECTORY_PATHS: ${{ inputs.directory-paths }}
      ENVIRONMENT: ${{inputs.environment}}
      BOS_SIGNER_PRIVATE_KEY: ${{ secrets.SIGNER_PRIVATE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set replacements
        id: set_replacements
        run: |
          cd "questverse-widgets/"
          echo "replacements=$(jq -r '[to_entries[] | .["find"] = "${" + .key + "}" | .["replace"] = .value | del(.key, .value)]' ../replacements.${ENVIRONMENT}.json | tr -d "\n\r")" >> $GITHUB_OUTPUT

      - name: Replace placeholders
        uses: flcdrg/replace-multiple-action@v1
        with:
          files: '**/*.jsx'
          find: '${{ steps.set_replacements.outputs.replacements }}'
          prefix: '(^|.*)'
          suffix: '($|.*)'

      - name: Install near-social CLI
        run: |
          curl --proto '=https' --tlsv1.2 -LsSf https://github.com/FroVolod/bos-cli-rs/releases/download/v${{ inputs.cli-version }}/bos-cli-v${{ inputs.cli-version }}-installer.sh | sh

      - name: Deploy widgets
        run: |
          for DIR in $(echo $DIRECTORY_PATHS | tr "," "\n")
          do
            cd "$DIR"
            bos components deploy "$BOS_DEPLOY_ACCOUNT_ID" sign-as "$BOS_DEPLOY_ACCOUNT_ID" network-config mainnet sign-with-plaintext-private-key --signer-public-key "$BOS_SIGNER_PUBLIC_KEY" --signer-private-key "$BOS_SIGNER_PRIVATE_KEY" send
            cd -
          done
