name: Deploy 'QuestVerse' App Components to Mainnet

on:
  push:
    branches: [main]
    paths:
      - "./questverse-widgets/apps/QuestVerse"

jobs:
  deploy-mainnet:
    uses: nearbuilders/bos-workspace/.github/workflows/deploy.yml@feat/git-workflows
    with:
      deploy-env: "mainnet"
      app-name: "QuestVerse"
      working-directory: "./questverse-widgets"
      deploy-account-address: ${{ vars.DEPLOY_ACCOUNT_ID }} 
      signer-account-address: ${{ vars.SIGNER_ACCOUNT_ID }}
      signer-public-key: ${{ vars.SIGNER_PUBLIC_KEY }}
    secrets: 
      SIGNER_PRIVATE_KEY: ${{ secrets.SIGNER_PRIVATE_KEY }}